In [108]:
import numpy as np
import pandas as pd

In [109]:
df = pd.read_csv("wine.csv",sep=";")
df


fixed_acidity  volatile_acidity  citric_acid  ...  sulphates  alcohol  quality
0               7.5              0.33         0.32  ...       0.34     10.5        6
1               6.3              0.27         0.29  ...       0.40      8.8        6
2               7.0              0.30         0.51  ...       0.52      9.6        7
3               7.4              0.38         0.27  ...       0.43       10        5
4               8.1              0.12         0.38  ...       0.55       12        6
...             ...               ...          ...  ...        ...      ...      ...
2032            8.1              0.34         0.28  ...       0.55      9.8        6
2033            7.4              0.19         0.31  ...       0.50      9.2        6
2034            6.7              0.36         0.26  ...       0.30     12.2        7
2035            7.7              0.28         0.35  ...       0.50      9.6        5
2036            5.7              0.22         0.28  ...       0.38     12.5        7

[2037 rows x 12 columns]

In [110]:
df['alcohol'] = pd.to_numeric(data['alcohol'],errors='coerce')
df['alcohol'].fillna(data['alcohol'].mean(), inplace = True)

In [111]:
lower_limit = df["free_sulfur_dioxide"].mean() - 3*df["free_sulfur_dioxide"].std()
upper_limit = df["free_sulfur_dioxide"].mean() + 3*df["free_sulfur_dioxide"].std()

In [112]:
df2 = df[(df["free_sulfur_dioxide"] > lower_limit) & (df["free_sulfur_dioxide"] < upper_limit)]

In [113]:
lower_limit = df2['total_sulfur_dioxide'].mean() - 3*df2['total_sulfur_dioxide'].std()
upper_limit = df2['total_sulfur_dioxide'].mean() + 3*df2['total_sulfur_dioxide'].std()

In [114]:
df3 = df2[(df2['total_sulfur_dioxide'] > lower_limit) & (df2['total_sulfur_dioxide'] < upper_limit)]

In [115]:
lower_limit = df3['residual_sugar'].mean() - 3*df3['residual_sugar'].std()
upper_limit = df3['residual_sugar'].mean() + 3*df3['residual_sugar'].std()

In [116]:
df4 = df3[(df3['residual_sugar'] > lower_limit) & (df3['residual_sugar'] < upper_limit)]

In [117]:
lower_limit = df4["chlorides"].mean() - 3*df4["chlorides"].std()
upper_limit = df4["chlorides"].mean() + 3*df4["chlorides"].std()

In [118]:
df5 = df4[(df4['chlorides'] > lower_limit) & (df4['chlorides'] < upper_limit)]
lower_limit = df5["sulphates"].mean() - 3*df5["sulphates"].std()
upper_limit = df5["sulphates"].mean() + 3*df5["sulphates"].std()

In [119]:
df6 = df5[(df5['sulphates'] > lower_limit) & (df5['sulphates'] < upper_limit)]
lower_limit = df6["volatile_acidity"].mean() - 3*df6["volatile_acidity"].std()
upper_limit = df6["volatile_acidity"].mean() + 3*df6["volatile_acidity"].std()

In [120]:
df7 = df6[(df6['volatile_acidity'] > lower_limit) & (df6['volatile_acidity'] < upper_limit)]
lower_limit = df7["fixed_acidity"].mean() - 3*df7["fixed_acidity"].std()
upper_limit = df7["fixed_acidity"].mean() + 3*df7["fixed_acidity"].std()

In [121]:
df8 = df7[(df7['fixed_acidity'] > lower_limit) & (df7['fixed_acidity'] < upper_limit)]
lower_limit = df8["citric_acid"].mean() - 3*df8["citric_acid"].std()
upper_limit = df8["citric_acid"].mean() + 3*df8["citric_acid"].std()

In [122]:
df9 = df8[(df8['citric_acid'] > lower_limit) & (df8['citric_acid'] < upper_limit)]
lower_limit = df9["pH"].mean() - 3*df9["pH"].std()
upper_limit = df9["pH"].mean() + 3*df9["pH"].std()

In [123]:
df10 = df9[(df9['pH'] > lower_limit) & (df9['pH'] < upper_limit)]

In [124]:
quality_mapping = { 3 : "Low", 4 : "Low", 5: "Medium",6 : "Medium",7: "Medium",8 : "High",9 : "High"}
df10["quality"] =  df10["quality"].map(quality_mapping)

In [125]:
quality_code = {"Low" : 0,"Medium": 1,"High" : 2}
df10["quality"] =  df10["quality"].map(quality_code)

In [126]:
train=df10

In [127]:
from sklearn.model_selection import train_test_split
X=train.drop(['quality'],axis=1)
y=train['quality']

In [128]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print(X.shape)

(2025, 11)


In [129]:
from sklearn.decomposition import PCA
pca = PCA()
x_pca = pca.fit_transform(X)

In [130]:
pca_new = PCA(n_components=10)
x_new = pca_new.fit_transform(X)

In [131]:
X_train, X_test, y_train, y_test = train_test_split(x_new, y, test_size = 0.2,random_state=1)

Models

In [132]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score
clf_ada = AdaBoostClassifier(n_estimators=100, random_state=0)
clf_ada.fit(X_train,y_train)
pred_ada=clf_ada.predict(X_test)
x_ada=accuracy_score(y_test,pred_ada)
print(f'the accuracy score is {x_ada}')

the accuracy score is 0.7802469135802469


In [133]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,pred_ada)
print(cm)

[[  2  11   1]
 [ 15 314  50]
 [  0  12   0]]


In [134]:
!pip3 install xgboost

In [135]:
import xgboost as xgb
model=xgb.XGBClassifier(n_estimators=400, random_state=42)
model.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=400, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [136]:
pred_xg=model.predict(X_test)

In [137]:
from sklearn.metrics import accuracy_score
x=accuracy_score(y_test,pred_xg)
print(f'the accuracy score is {x}')

the accuracy score is 0.9333333333333333


In [138]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,pred_xg)
print(cm)

[[  0  14   0]
 [  0 376   3]
 [  0  10   2]]


In [139]:
!pip3 install catboost

In [140]:
from catboost import CatBoostClassifier
clf = CatBoostClassifier(iterations=100,  learning_rate=0.1)
clf.fit(X_train,y_train)

0:	learn: 0.9524646	total: 8.38ms	remaining: 830ms
1:	learn: 0.8433881	total: 15.3ms	remaining: 750ms
2:	learn: 0.7522715	total: 22.3ms	remaining: 722ms
3:	learn: 0.6819531	total: 29.1ms	remaining: 700ms
4:	learn: 0.6178462	total: 36ms	remaining: 685ms
5:	learn: 0.5687483	total: 42.7ms	remaining: 670ms
6:	learn: 0.5280112	total: 49.6ms	remaining: 659ms
7:	learn: 0.4900132	total: 56.7ms	remaining: 652ms
8:	learn: 0.4558805	total: 63.6ms	remaining: 643ms
9:	learn: 0.4257214	total: 70.3ms	remaining: 633ms
10:	learn: 0.4018671	total: 77.1ms	remaining: 624ms
11:	learn: 0.3785114	total: 84ms	remaining: 616ms
12:	learn: 0.3601597	total: 92.1ms	remaining: 616ms
13:	learn: 0.3428438	total: 98.7ms	remaining: 606ms
14:	learn: 0.3260459	total: 105ms	remaining: 597ms
15:	learn: 0.3127812	total: 112ms	remaining: 589ms
16:	learn: 0.3005252	total: 119ms	remaining: 580ms
17:	learn: 0.2890829	total: 126ms	remaining: 572ms
18:	learn: 0.2797622	total: 132ms	remaining: 564ms
19:	learn: 0.2698386	total: 139

In [141]:
pred_cat=clf.predict(X_test)

In [142]:
x_cat=accuracy_score(y_test,pred_cat)
print(f'the accuracy score is {x_cat}')

the accuracy score is 0.9358024691358025


In [143]:
cm= confusion_matrix(y_test,pred_cat)
print(cm)

[[  0  14   0]
 [  0 379   0]
 [  0  12   0]]


In [144]:
from lightgbm import LGBMClassifier
model_ = LGBMClassifier(n_estimators=100,num_leaves=35,learning_rate=0.1,max_bin=255,max_depth=-1)
model_.fit(X_train,y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_bin=255,
               max_depth=-1, min_child_samples=20, min_child_weight=0.001,
               min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=35,
               objective=None, random_state=None, reg_alpha=0.0, reg_lambda=0.0,
               silent=True, subsample=1.0, subsample_for_bin=200000,
               subsample_freq=0)

In [145]:
pred_lgm=model_.predict(X_test)

In [146]:
x_lgm=accuracy_score(y_test,pred_lgm)
print(f'the accuracy score is {x_lgm}')

the accuracy score is 0.9407407407407408


In [147]:
cm= confusion_matrix(y_test,pred_lgm)
print(cm)

[[  0  14   0]
 [  0 379   0]
 [  0  10   2]]


In [148]:
from sklearn.ensemble import BaggingClassifier
clf_2 = BaggingClassifier(base_estimator= LGBMClassifier(), n_estimators=200).fit(X_train,y_train)
pred_bag_=clf_2.predict(X_test)
x_bag_=accuracy_score(y_test,pred_bag_)
print(f'the accuracy score is {x_bag_}')

the accuracy score is 0.9407407407407408


In [149]:
cm= confusion_matrix(y_test,pred_bag_)
print(cm)

[[  0  14   0]
 [  0 379   0]
 [  0  10   2]]


In [150]:
clf_3 = BaggingClassifier(base_estimator= CatBoostClassifier(), n_estimators=40).fit(X_train,y_train)
pred_bag_c=clf_3.predict(X_test)
x_bag_c=accuracy_score(y_test,pred_bag_c)
print(f'the accuracy score is {x_bag_c}')

Streaming output truncated to the last 5000 lines.
5:	learn: 0.6188695	total: 47.2ms	remaining: 7.82s
6:	learn: 0.5760252	total: 55.9ms	remaining: 7.93s
7:	learn: 0.5360893	total: 64.5ms	remaining: 8s
8:	learn: 0.4994054	total: 72ms	remaining: 7.93s
9:	learn: 0.4678773	total: 80.3ms	remaining: 7.95s
10:	learn: 0.4407533	total: 87.7ms	remaining: 7.89s
11:	learn: 0.4146452	total: 95.2ms	remaining: 7.84s
12:	learn: 0.3936986	total: 103ms	remaining: 7.83s
13:	learn: 0.3720486	total: 111ms	remaining: 7.79s
14:	learn: 0.3527540	total: 118ms	remaining: 7.72s
15:	learn: 0.3364471	total: 126ms	remaining: 7.73s
16:	learn: 0.3215538	total: 136ms	remaining: 7.85s
17:	learn: 0.3066902	total: 143ms	remaining: 7.79s
18:	learn: 0.2934921	total: 150ms	remaining: 7.72s
19:	learn: 0.2816339	total: 157ms	remaining: 7.68s
20:	learn: 0.2712002	total: 164ms	remaining: 7.65s
21:	learn: 0.2621784	total: 172ms	remaining: 7.66s
22:	learn: 0.2532785	total: 180ms	remaining: 7.63s
23:	learn: 0.2451490	total: 187ms	

In [151]:
cm= confusion_matrix(y_test,pred_bag_c)
print(cm)

[[  0  14   0]
 [  0 378   1]
 [  0  11   1]]


In [152]:
clf_4 = BaggingClassifier(base_estimator= xgb.XGBClassifier(), n_estimators=200,random_state=50).fit(X_train,y_train)
pred_bag_xg=clf_4.predict(X_test)
x_bag_xg=accuracy_score(y_test,pred_bag_xg)
print(f'the accuracy score is {x_bag_xg}')

the accuracy score is 0.9358024691358025


In [153]:
cm= confusion_matrix(y_test,pred_bag_xg)
print(cm)

[[  0  14   0]
 [  0 379   0]
 [  0  12   0]]


In [154]:
clf_5 = BaggingClassifier(base_estimator= AdaBoostClassifier(), n_estimators=200).fit(X_train,y_train)
pred_bag_ada=clf_5.predict(X_test)
x_bag_ada=accuracy_score(y_test,pred_bag_ada)
print(f'the accuracy score is {x_bag_ada}')

the accuracy score is 0.891358024691358


In [155]:
cm= confusion_matrix(y_test,pred_bag_ada)
print(cm)

[[  1  13   0]
 [  0 359  20]
 [  0  11   1]]
